// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDysJvygELdeI6d_U1ZEE32lkKeFm09fOI',
    appId: '1:347510462029:web:05bd346d67f5d823862e04',
    messagingSenderId: '347510462029',
    projectId: 'bancoazteca-24875',
    authDomain: 'bancoazteca-24875.firebaseapp.com',
    storageBucket: 'bancoazteca-24875.appspot.com',
    measurementId: 'G-HNJ0YDYYF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLO1CYqB9T51bAG_Z71pEh8oj00is-h8',
    appId: '1:347510462029:android:dd1ded3b9eeadd3c862e04',
    messagingSenderId: '347510462029',
    projectId: 'bancoazteca-24875',
    storageBucket: 'bancoazteca-24875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIgZFr9VJlNhpRGcFD1bx8EA1qJHhCvto',
    appId: '1:347510462029:ios:42e3892dc428d7fb862e04',
    messagingSenderId: '347510462029',
    projectId: 'bancoazteca-24875',
    storageBucket: 'bancoazteca-24875.appspot.com',
    iosClientId: '347510462029-m1c2j6pu3ipn10rg0u4ivg8snsljea8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bancoAzteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIgZFr9VJlNhpRGcFD1bx8EA1qJHhCvto',
    appId: '1:347510462029:ios:42e3892dc428d7fb862e04',
    messagingSenderId: '347510462029',
    projectId: 'bancoazteca-24875',
    storageBucket: 'bancoazteca-24875.appspot.com',
    iosClientId: '347510462029-m1c2j6pu3ipn10rg0u4ivg8snsljea8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.bancoAzteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDysJvygELdeI6d_U1ZEE32lkKeFm09fOI',
    appId: '1:347510462029:web:276f6485a9b34086862e04',
    messagingSenderId: '347510462029',
    projectId: 'bancoazteca-24875',
    authDomain: 'bancoazteca-24875.firebaseapp.com',
    storageBucket: 'bancoazteca-24875.appspot.com',
    measurementId: 'G-F9JCXXLBCD',
  );
}
